#services:
#  prometheus:
#    image: prom/prometheus:v2.35.0
#    network_mode: host
#    container_name: prometheus
#    restart: unless-stopped
#    volumes:
#      - ./data/prometheus/config:/etc/prometheus/
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yaml"
#    ports:
#      - 9090:9090
#
#  grafana:
#    image: grafana/grafana-oss:8.5.2
#    pull_policy: always
#    network_mode: host
#    container_name: grafana
#    restart: unless-stopped
#    user: root
#    ports:
#      - 3000:3000 # access grafana url
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USERS_ALLOW_SIGN_UP=false
#      - GF_SERVER_DOMAIN=localhost



version: "3.7"
services:
  mysqldb:
    image: "mysql:8.3.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: questionnaireDB
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD:

  api_service:
    build: .
    restart: always
    ports:
      - 8086:8086
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/questionnaireDB
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2
networks:
  springapimysql-net: